import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nathan's Clubhouse",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="p-8 pb-4 bg-linear-to-b from-gray-700 to-gray-800">
      <div>
        <h1 className="my-8 mb-16 font-bold text-6xl text-white mx-4 italic">
          Nathan's Clubhouse
        </h1>
      </div>
      <div>
        <nav className="flex flex-wrap justify-start">
          <div className="bg-linear-to-b from-gray-700 to-gray-900 hover:from-gray-600 hover:to-gray-900 active:from-gray-900 active:to-gray-800 text-white font-bold m-4 rounded-md select-none">
            <Link 
            href="/"
            className="inline-block p-4 px-16">Home</Link>
          </div>
          <div className="bg-linear-to-b from-gray-700 to-gray-900 hover:from-gray-600 hover:to-gray-900 active:from-gray-900 active:to-gray-800 text-white font-bold m-4 rounded-md select-none">
            <Link 
            href="/websites"
            className="inline-block p-4 px-16">Websites</Link>
          </div>
          <div className="bg-linear-to-b from-gray-700 to-gray-900 hover:from-gray-600 hover:to-gray-900 active:from-gray-900 active:to-gray-800 text-white font-bold m-4 rounded-md select-none">
            <Link 
            href="/android"
            className="inline-block p-4 px-16">Android</Link>
          </div>
          <div className="bg-linear-to-b from-gray-700 to-gray-900 hover:from-gray-600 hover:to-gray-900 active:from-gray-900 active:to-gray-800 text-white font-bold m-4 rounded-md select-none">
            <a 
            href="https://github.com/PapsBurr" 
            target="_blank"
            className="inline-block p-4 px-16">GitHub</a>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
