import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nathan's Clubhouse",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="p-8 bg-linear-to-b from-gray-600 to-gray-700">
      <div>
        <h1 className="my-8 mb-16 font-bold text-6xl text-white mx-4 italic">
          Nathan's Clubhouse
          </h1>
      </div>
      <div>
        <nav className="flex justify-start">
          <div>
            <Link 
            href="/" 
            className="bg-linear-to-b from-gray-600 to-gray-800 hover:from-gray-300 to hover:gray-600 active:gray-sky-900 active:to-gray-800 text-white font-bold p-4 mx-4 px-16 rounded-md">Home</Link>
          </div>
          <div>
            <Link 
            href="/websites" 
            className="bg-linear-to-b from-gray-600 to-gray-800 hover:from-gray-300 to hover:gray-600 active:gray-sky-900 active:to-gray-800 text-white font-bold p-4 mx-4 px-16 rounded-md">Websites</Link>
          </div>
          <div>
            <Link 
            href="/android" 
            className="bg-linear-to-b from-gray-600 to-gray-800 hover:from-gray-300 to hover:gray-600 active:gray-sky-900 active:to-gray-800 text-white font-bold p-4 mx-4 px-16 rounded-md">Android</Link>
          </div>
          <div>
            <a 
            href="https://github.com/PapsBurr" 
            target="_blank"
            className="bg-linear-to-b from-gray-600 to-gray-800 hover:from-gray-300 to hover:gray-600 active:gray-sky-900 active:to-gray-800 text-white font-bold p-4 mx-4 px-16 rounded-md">GitHub</a>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
