import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nathan's Résumé",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="py-8 px-16 bg-gray-800">
      <div>
        <h1 className="my-8 font-bold text-6xl">Nathan's Résumé</h1>
      </div>
      <div>
        <nav className="flex justify-between">
          <div className="bg-sky-800 text-white font-bold p-2 px-10 rounded-md">
            <Link href="/">Home</Link>
          </div>
          <div className="bg-sky-800 text-white font-bold p-2 px-10 rounded-md">
            <Link href="/">Home</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
