import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nathan's website",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="p-8 bg-gray-600">
      <div>
        <h1 className="my-8 mb-16 font-bold text-6xl text-white mx-4">Nathan's website</h1>
      </div>
      <div>
        <nav className="flex justify-start">
          <div>
            <Link href="/" className="bg-sky-500 hover:bg-sky-400 text-white font-bold p-4 mx-4 px-16 rounded-md">Home</Link>
          </div>
          <div>
            <Link href="/android" className="bg-sky-500 hover:bg-sky-400 text-white font-bold p-4 mx-4 px-16 rounded-md">Android</Link>
          </div>
          <div>
            <a href="https://github.com/PapsBurr" className="bg-sky-500 hover:bg-sky-400 text-white font-bold p-4 mx-4 px-16 rounded-md">GitHub</a>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
